/**
 * Login
 */
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME';
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';
export const RESET_LOGIN_CREDENTIALS = 'RESET_LOGIN_CREDENTIALS';

/**
 * Register
 */
export const CHANGE_REGISTER_FIRSTNAME = 'CHANGE_REGISTER_FIRSTNAME';
export const CHANGE_REGISTER_LASTNAME = 'CHANGE_REGISTER_LASTNAME';
export const CHANGE_REGISTER_DOB = 'CHANGE_REGISTER_DOB';
export const CHANGE_REGISTER_EMAIL = 'CHANGE_REGISTER_EMAIL';
export const CHANGE_REGISTER_USERNAME = 'CHANGE_REGISTER_USERNAME';
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD';
export const CHANGE_REGISTER_PASSWORD2 = 'CHANGE_REGISTER_PASSWORD2';
export const CHANGE_REGISTER_ROLE = 'CHANGE_REGISTER_ROLE';
export const CHANGE_REGISTER_DESCRIPTION = 'CHANGE_REGISTER_DESCRIPTION';
export const RESET_REGISTER_CREDENTIALS = 'RESET_REGISTER_CREDENTIALS';

/**
 * Alerts
 */
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const SET_NO_FAN_FOLLOWING_ALERT = 'SET_NO_FAN_FOLLOWING_ALERT';
export const SET_NO_FOLLOWERS_ALERT = 'SET_NO_FOLLOWERS_ALERT';
export const SET_NO_CRITIC_FOLLOWING_ALERT = 'SET_NO_CRITIC_FOLLOWING_ALERT';
export const SET_NO_ACTORS_FOLLOWED_ALERT = 'SET_NO_ACTORS_FOLLOWED_ALERT';
export const SET_NO_MOVIES_LIKED_ALERT = 'SET_NO_MOVIES_LIKED_ALERT';
export const SET_NO_MOVIES_REVIEWED_ALERT = 'SET_NO_MOVIES_REVIEWED_ALERT';
export const SET_NO_MOVIES_RECOMMENDED_ALERT = 'SET_NO_MOVIES_RECOMMENDED_ALERT';
export const SET_LIKED_ALERT = 'SET_LIKED_ALERT';
export const SET_REVIEWED_ALERT = 'SET_REVIEWED_ALERT';
export const SET_FOLLOWED_ACTOR_ALERT = 'SET_FOLLOWED_ACTOR_ALERT';
export const SET_UNFOLLOWED_USER_ALERT = 'SET_UNFOLLOWED_USER_ALERT';
export const SET_FOLLOWED_USER_ALERT = 'SET_FOLLOWED_USER_ALERT';
export const SET_RECOMMENDED_ALERT = 'SET_RECOMMENDED_ALERT';
export const SET_DELETE_RECOMMENDED_MOVIE_ALERT = 'SET_DELETE_RECOMMENDED_MOVIE_ALERT';
export const SET_DELETE_LIKED_MOVIE_ALERT = 'SET_DELETE_LIKED_MOVIE_ALERT';
export const SET_DELETE_ACTOR_FOLLOWED_ALERT = 'SET_DELETE_ACTOR_FOLLOWED_ALERT';
export const SET_REMOVE_USER_ALERT = 'SET_REMOVE_USER_ALERT';
export const SET_ALREADY_LIKED_ALERT = 'SET_ALREADY_LIKED_ALERT';
export const SET_ALREADY_FOLLOW_ACTOR_ALERT = 'SET_ALREADY_FOLLOW_ACTOR_ALERT';
export const SET_ALREADY_FOLLOWED_USER_ALERT = 'SET_ALREADY_FOLLOWED_USER_ALERT';

/**
 * Set and Reset
 */
export const SET = 'SET';
export const RESET = 'RESET';
export const SET_FOLLOW_BUTTON = 'SET_FOLLOW_BUTTON';

/**
 * Movie
 */
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const MOVIE_DETAILS = 'MOVIE_DETAILS';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const SHOW_REVIEW_MODAL = 'SHOW_REVIEW_MODAL';

/**
 * User
 */

export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_MOVIES_LIKED = 'GET_MOVIES_LIKED';
export const GET_MOVIES_REVIEWED = 'GET_MOVIES_REVIEWED';
export const GET_MOVIES_RECOMMENDED = 'GET_MOVIES_RECOMMENDED';
export const ACTIVATE_FOLLOWERS_PILL = 'ACTIVATE_FOLLOWERS_PILL';
export const ACTIVATE_FAN_FOLLOWING_PILL = 'ACTIVATE_FAN_FOLLOWING_PILL';
export const ACTIVATE_CRITIC_FOLLOWING_PILL = 'ACTIVATE_CRITIC_FOLLOWING_PILL';
export const ACTIVATE_ACTOR_FOLLOWING_PILL = 'ACTIVATE_ACTOR_FOLLOWING_PILL';
export const ACTIVATE_MOVIE_LIKE_PILL = 'ACTIVATE_MOVIE_LIKE_PILL';
export const ACTIVATE_MOVIE_REVIEW_PILL = 'ACTIVATE_MOVIE_REVIEW_PILL';
export const ACTIVATE_MOVIE_RECOMMEND_PILL = 'ACTIVATE_MOVIE_RECOMMEND_PILL';
export const GET_CRITICS_FOLLOWED = 'GET_CRITICS_FOLLOWED';
export const SEARCH_USERS = 'SEARCH_USERS';
export const CHANGE_RATING = 'CHANGE_RATING';
export const CHANGE_REVIEW_TEXT = 'CHANGE_REVIEW_TEXT';

/**
 * Actor
 */
export const GET_ACTORS_FOLLOWED = 'GET_ACTORS_FOLLOWED';
export const SEARCH_ACTORS = 'SEARCH_ACTORS';
export const ACTOR_DETAILS = 'ACTOR_DETAILS';