/**
 * Login
 */
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME';
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';
export const RESET_LOGIN_CREDENTIALS = 'RESET_LOGIN_CREDENTIALS';

/**
 * Register
 */
export const CHANGE_REGISTER_FIRSTNAME = 'CHANGE_REGISTER_FIRSTNAME';
export const CHANGE_REGISTER_LASTNAME = 'CHANGE_REGISTER_LASTNAME';
export const CHANGE_REGISTER_DOB = 'CHANGE_REGISTER_DOB';
export const CHANGE_REGISTER_EMAIL = 'CHANGE_REGISTER_EMAIL';
export const CHANGE_REGISTER_USERNAME = 'CHANGE_REGISTER_USERNAME';
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD';
export const CHANGE_REGISTER_PASSWORD2 = 'CHANGE_REGISTER_PASSWORD2';
export const CHANGE_REGISTER_ROLE = 'CHANGE_REGISTER_ROLE';
export const CHANGE_REGISTER_DESCRIPTION = 'CHANGE_REGISTER_DESCRIPTION';
export const RESET_REGISTER_CREDENTIALS = 'RESET_REGISTER_CREDENTIALS';

/**
 * Alerts
 */
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';

/**
 * Set and Reset
 */
export const SET = 'SET';
export const RESET = 'RESET';

/**
 * Movie
 */
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const MOVIE_DETAILS = 'MOVIE_DETAILS';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const SET_LIKED_ALERT = 'SET_LIKED_ALERT';
export const SET_FOLLOWED_ALERT = 'SET_FOLLOWED_ALERT';
export const SET_RECOMMENDED_ALERT = 'SET_RECOMMENDED_ALERT';
export const SHOW_REVIEW_MODAL = 'SHOW_REVIEW_MODAL';

/**
 * User
 */

export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_MOVIES_LIKED = 'GET_MOVIES_LIKED';

/**
 * Actor
 */
export const GET_ACTORS_FOLLOWED = 'GET_ACTORS_FOLLOWED';